-- Content Studio candidates are intentionally registered before Precache() runs.
-- The catalog itself remains server-owned; this list only makes the vetted,
-- locally VPK-verified preview resources resident in Tools Mode.
local PARTICLES = {
	"particles/econ/events/fall_2022/player/fall_2022_emblem_effect_player_base.vpcf",
	"particles/econ/events/fall_2022/regen/fountain_regen_fall2022_lvl3.vpcf",
	"particles/econ/events/ti10/aghanim_aura_ti10/agh_aura_ti10.vpcf",
	"particles/econ/events/ti10/fountain_regen_ti10_lvl3.vpcf",
	"particles/econ/events/ti10/hero_levelup_ti10.vpcf",
	"particles/econ/events/ti10/high_five/high_five_lvl2_impact.vpcf",
	"particles/econ/events/ti10/high_five/high_five_lvl2_overhead.vpcf",
	"particles/econ/events/ti10/high_five/high_five_lvl2_travel.vpcf",
	"particles/econ/events/ti10/radiance_owner_ti10.vpcf",
	"particles/econ/events/ti10/radiance_ti10.vpcf",
	"particles/econ/events/ti10/teleport/teleport_end_ti10_lvl2.vpcf",
	"particles/econ/events/ti10/teleport/teleport_start_ti10_lvl2.vpcf",
	"particles/econ/events/ti4/radiant_fountain_regen_ti4.vpcf",
	"particles/econ/events/ti4/teleport_end_ti4.vpcf",
	"particles/econ/events/ti4/teleport_start_ti4.vpcf",
	"particles/econ/events/ti5/radiant_fountain_regen_lvl2_ti5.vpcf",
	"particles/econ/events/ti5/teleport_end_lvl2_ti5.vpcf",
	"particles/econ/events/ti5/teleport_start_lvl2_ti5.vpcf",
	"particles/econ/events/ti6/hero_levelup_ti6.vpcf",
	"particles/econ/events/ti6/bottle_ti6.vpcf",
	"particles/econ/events/ti6/radiance_owner_ti6.vpcf",
	"particles/econ/events/ti6/radiance_ti6.vpcf",
	"particles/econ/events/ti6/radiant_fountain_regen_ti6_lvl3.vpcf",
	"particles/econ/events/ti6/teleport_end_ti6_lvl3.vpcf",
	"particles/econ/events/ti6/teleport_start_ti6_lvl3.vpcf",
	"particles/econ/events/ti7/fountain_regen_ti7_lvl3.vpcf",
	"particles/econ/events/ti7/bottle_ti7.vpcf",
	"particles/econ/events/ti7/hero_levelup_ti7.vpcf",
	"particles/econ/events/ti7/teleport_end_ti7_lvl3.vpcf",
	"particles/econ/events/ti7/teleport_start_ti7_lvl3.vpcf",
	"particles/econ/events/ti8/fountain_regen_ti8_lvl3.vpcf",
	"particles/econ/events/ti8/hero_levelup_ti8.vpcf",
	"particles/econ/events/ti8/radiance_owner_ti8.vpcf",
	"particles/econ/events/ti8/radiance_ti8.vpcf",
	"particles/econ/events/ti8/teleport_end_ti8_lvl3.vpcf",
	"particles/econ/events/ti8/teleport_start_ti8_lvl3.vpcf",
	"particles/econ/events/ti9/fountain_regen_ti9_lvl3.vpcf",
	"particles/econ/events/ti9/bottle_ti9.vpcf",
	"particles/econ/events/ti9/hero_levelup_ti9.vpcf",
	"particles/econ/events/ti9/high_five/high_five_impact.vpcf",
	"particles/econ/events/ti9/high_five/high_five_overhead.vpcf",
	"particles/econ/events/ti9/high_five/high_five_travel.vpcf",
	"particles/econ/events/ti9/radiance_owner_ti9.vpcf",
	"particles/econ/events/ti9/radiance_ti9.vpcf",
	"particles/econ/events/ti9/teleport_end_ti9_lvl3.vpcf",
	"particles/econ/events/ti9/teleport_start_ti9_lvl3.vpcf",
	"models/heroes/muerta/debut/particles/revenant/muerta_debut_revenant_spawn_portal.vpcf",
	"particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/cm_arcana_pup_spawn.vpcf",
	"particles/econ/items/earthshaker/earthshaker_arcana/earthshaker_arcana_spawn_v2.vpcf",
	"particles/econ/items/faceless_void/faceless_void_arcana/faceless_void_arcana_game_spawn.vpcf",
	"particles/econ/items/ogre_magi/ogre_magi_arcana/ogre_magi_arcana_loadout_spawn.vpcf",
	"particles/econ/items/phantom_lancer/phantom_lancer_fall20_immortal/phantom_lancer_fall20_immortal_spawn.vpcf",
	"particles/econ/items/spectre/spectre_arcana/spectre_arcana_loadout_spawn_v2.vpcf",
	"particles/econ/items/shadow_demon/sd_ti7_shadow_poison/sd_ti7_golden_shadow_poison_kill.vpcf",
	"particles/econ/items/shadow_demon/sd_ti7_shadow_poison/sd_ti7_shadow_poison_kill.vpcf",
	"particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_arcana_enemy_death.vpcf",
	"particles/econ/items/windrunner/windranger_arcana/windranger_arcana_tgt_death.vpcf",
	"particles/econ/items/windrunner/windranger_arcana/windranger_arcana_tgt_death_v2.vpcf",
	"particles/generic_gameplay/generic_lifesteal.vpcf",
	"particles/items3_fx/octarine_core_lifesteal.vpcf",
	"particles/items2_fx/ward_spawn_generic.vpcf",
	"particles/items_fx/bloodstone_heal.vpcf",
	"particles/neutral_fx/roshan_spawn.vpcf",
	"particles/ui/ui_game_start_hero_spawn.vpcf",
	"particles/units/heroes/hero_abaddon/abaddon_spawn.vpcf",
	"particles/units/heroes/hero_death_prophet/death_prophet_spawn.vpcf",
	"particles/units/heroes/hero_faceless_void/faceless_void_spawn.vpcf",
	"particles/units/heroes/hero_invoker_kid/invoker_kid_debut_spawn.vpcf",
	"particles/units/heroes/hero_life_stealer/life_stealer_health_steal_plus.vpcf",
	"particles/units/heroes/hero_phantom_lancer/phantom_lancer_spawn.vpcf",
	"particles/units/heroes/hero_winter_wyvern/wyvern_spawn.vpcf",
}

if IsInToolsMode ~= nil and IsInToolsMode()
	and GetMapName ~= nil and string.lower(GetMapName() or "") == "x_hero_siege_demo"
	and XHSPrecache ~= nil and XHSPrecache.RegisterGroup ~= nil then
	XHSPrecache:RegisterGroup("supporter_content_studio", {
		particles = PARTICLES,
	})
end

return PARTICLES
