if IsClient() then
	LinkLuaModifier("modifier_provides_fow_position", "modifiers/modifier_provides_fow_position", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_npc_dialog", "modifiers/modifier_npc_dialog", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_npc_dialog_notify", "modifiers/modifier_npc_dialog_notify", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stack_count_animation_controller", "modifiers/modifier_stack_count_animation_controller", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_disable_aggro", "modifiers/modifier_disable_aggro", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_tome_of_stats", "items/tomes.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_pause_creeps", "modifiers/modifier_pause_creeps.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_cinematic_pause", "modifiers/modifier_cinematic_pause.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_cinematic_pause_release", "modifiers/modifier_cinematic_pause.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_custom_mechanics", "modifiers/modifier_custom_mechanics", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_growth_overhead", "modifiers/modifier_xhs_growth_overhead.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_holdout_taunt_debuff", "abilities/heroes/hero_paladin.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_orb_of_arcane", "items/item_orb_of_arcane.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_orb_of_arcane_active", "items/item_orb_of_arcane.lua", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_orb_of_arcane_exposure", "items/item_orb_of_arcane.lua", LUA_MODIFIER_MOTION_NONE)

	local xhsRuneModifierScript = "components/runes/modifiers.lua"
	LinkLuaModifier("modifier_xhs_rune_healing", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_revitalization", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_restoration", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_second_wind", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_second_wind_heal", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_second_wind_guard", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_barrier", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_retaliation", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_bulwark", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_fortitude", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_titan", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_fury", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_siegebreaker", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_storm", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_bounty_surge", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_xhs_rune_momentum", xhsRuneModifierScript, LUA_MODIFIER_MOTION_NONE)
end
